feat(effects): remove act operator
Closes #4837

BREAKING CHANGES:

The `act` operator is removed in favor of core RxJS flattening operators and `mapResponse` from the `@ngrx/operators` package.

BEFORE:

@Injectable()
export class AuthEffects {
  readonly login$ = createEffect(() => {
    return this.actions$.pipe(
      ofType(LoginPageActions.loginFormSubmitted),
      act({
        project: ({ credentials }) =>
          this.authService
            .login(credentials)
            .pipe(map((user) => AuthApiActions.loginSuccess({ user }))),
        error: (error) => AuthApiActions.loginFailure({ error }),
        operator: exhaustMap,
      })
    );
  });
}

AFTER:

@Injectable()
export class AuthEffects {
  readonly login$ = createEffect(() => {
    return this.actions$.pipe(
      ofType(LoginPageActions.loginFormSubmitted),
      exhaustMap(({ credentials }) =>
        this.authService.login(credentials).pipe(
          mapResponse({
            next: (user) => AuthApiActions.loginSuccess({ user }),
            error: (error) => AuthApiActions.loginFailure({ error }),
          })
        )
      )
    );
  });
}