feat(operators): remove deprecated tapResponse signature (#5153)
BREAKING CHANGES:

The deprecated callback-style signature of tapResponse is removed.

BEFORE:

The callback signature could be used.

tapResponse(
  (value) => { },
  (error) => { },
  () => { }, // optional
);

AFTER:

Use the object-style signature.

tapResponse({
  next: (value) => { },
  error: (error) => { },
  complete: () => { },
});